### ISSUE TITLE
Not scrobbling on Spotify Web Scrobbler through another device or tab

### ISSUE THREAD

**Issue by perfectvelvet** [web-scrobbler/web-scrobbler#2289]
When I play music from the Spotify mobile app, I usually open the Spotify web player so that the Last.fm Web Scrobbler scrobbles the music. It worked perfectly until recently. Now it says "Play some music to get started" although I'm already playing music, even if it's from a different device.

**How to reproduce**
1. Play music on Spotify on your phone
2. Go to "open.spotify.com" on Google Chrome on your computer
3. Click the Last.fm Web Scrobbler icon and it should say "Play some music to get started", not realizing that you already are playing music from another device.

**Expected behavior**
It's supposed to recognize and scrobble the track when the track is half finished.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.28.3

Update: Now it's not scrobbling through the Web Scrobbler at all, on any tab. Now it says "Play some music to get started" when I am playing music on the only active tab.

**Comment by jaccarmac** [comment]
See the conversation in #2276. This appears to be a known issue which will be fixed in the next release.

**Comment by alexesprit** [comment]
Yes, it was fixed.

**Comment by perfectvelvet** [comment]
It wasn't for me.

**Comment by perfectvelvet** [comment]
Now it isn't scrobbling through the web player at all. Just "Play some music to get started" even though I am playing music on that exact tab. The issue got bigger I guess, not fixed.

**Comment by alexesprit** [comment]
When I was saying it's fixed, I didn't mean it's published.

**Comment by folsomwg** [comment]
> When I was saying it's fixed, I didn't mean it's published.

Lets get that bad boy published.

**Comment by alexesprit** [comment]
I'm closing this issue, as it was fixed. The new behavior (https://github.com/web-scrobbler/web-scrobbler/issues/2276#issuecomment-592918479) will be available in the next minor release.
