### ISSUE TITLE
YouTube not scrobbling in FireFox

### ISSUE THREAD

**Issue by KatyLB** [web-scrobbler/web-scrobbler#2368]
**Describe the bug**
YouTube is not scrobbling in FireFox. I've updated to the last version of Web Scrobbler, and tried the various category settings in options, but it's still not working.

Nothing will scrobble, including:

https://www.youtube.com/watch?v=SSbBvKaM6sk
https://www.youtube.com/watch?v=Az_GCJnXAI0
https://www.youtube.com/watch?v=va6nPu-1auE
https://www.youtube.com/watch?v=Re4aDJL3heA

The scrobble icon is red and it gives the "Play some music to get started. Is it already playing?" message.

I think this only started today and I haven't changed anything at my end.

**How to reproduce**
1. Attempt to scrobble any video on YouTube in Firefox

**Expected behavior**
Web Scrobbler should indicate the track is playing and scrobble it correctly.

**Screenshots**
N/A

**Environment (please complete the following information)**
Windows 10, Firefox 69.0.3

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by KatyLB** [comment]
I tried to do that, the "Debug" option I'm supposed to click in the instructions isn't there. I just have this:

![image](https://user-images.githubusercontent.com/37089178/79690600-1c7be700-8253-11ea-98f0-28b4a994d99c.png)

If I click "Inspect" and then "Debugger" I just get this screen:

![image](https://user-images.githubusercontent.com/37089178/79690619-30bfe400-8253-11ea-880c-e3298dd22907.png)

**Comment by KatyLB** [comment]
I got the "Logs of content scripts" bit though:

`Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. base.js:5224:33
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. base.js:1012:334
Web Scrobbler: Setting up observer util.js:392:3
Web Scrobbler: Player element (#content) was not found in the page util.js:392:3
Web Scrobbler: Found #content using second MutationObserver. util.js:392:3
method `computeYoodleData` not defined 2 desktop_polymer_inlined_html_polymer_flags_v2.js:7167:150
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. base.js:5224:33
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).
Loading failed for the <script> with source “https://static.doubleclick.net/instream/ad_status.js”. watch:1:1`

**Comment by alexesprit** [comment]
You should click on "Inspect" button.

Have you tried to use newer Firefox? What your extension version?

**Comment by KatyLB** [comment]
This is the console tab after I clicked inspect and tried a video, is this what you meant?

`The script from “https://data.alexa.com/app/js/3rd/jquery.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. apps.html
The script from “https://data.alexa.com/app/js/3rd/URI.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. apps.html
The script from “https://data.alexa.com/app/js/apps.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. apps.html
storage.Options = {
  "disabledConnectors": "[hidden]",
  "disableGa": true,
  "forceRecognize": true,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": true,
  "scrobblePodcasts": true,
  "scrobblePercent": 50
} wrapper.js:68:12
storage.Connectors = {
  "YouTube": {
    "scrobbleMusicOnly": true,
    "scrobbleEntertainmentOnly": true
  },
  "Tidal": {
    "useShortTrackNames": false
  }
} wrapper.js:68:12
The script from “https://data.alexa.com/app/js/3rd/jquery.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/3rd/md5.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/3rd/base64.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/3rd/URI.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/dc/helper.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/dc/overlay.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/dc/results.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
The script from “https://data.alexa.com/app/js/dc/messages.js?random=20180524” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. dc.html
storage.ListenBrainz = {} wrapper.js:68:12
storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "*************"
} wrapper.js:68:12
storage.LibreFM = {} wrapper.js:68:12
storage.Core = {
  "appVersion": "2.30.5"
} wrapper.js:68:12
Bind Last.fm scrobbler scrobble-service.js:63:13
Unable to bind Libre.fm scrobble-service.js:49:14
Unable to bind ListenBrainz scrobble-service.js:49:14
Injecting vendor/filter.js inject.js:52:12
Injecting vendor/jquery.min.js inject.js:52:12
Injecting vendor/browser-polyfill.min.js inject.js:52:12
Injecting core/content/util.js inject.js:52:12
Injecting core/content/reactor.js inject.js:52:12
Injecting core/content/connector.js inject.js:52:12
Injecting connectors/youtube.js inject.js:52:12
Injecting core/content/starter.js inject.js:52:12
Tab 3: Created controller for YouTube connector util.js:147:3
`

It's the newest version of the extension and it only just stopped working, I haven't changed my Firefox version.

**Comment by KatyLB** [comment]
Updated to Firefox 75.0 and still not working.

**Comment by alexesprit** [comment]
Unfortunately, I don't know why it does not work. Cannot reproduce it on Windows 10, Firefox 75.

Does scrobbling from other websites work for you?

**Comment by alexesprit** [comment]
Could you also downgrade to previous extension versions and check them?

**Comment by KatyLB** [comment]
Yes, other sites like Bandcamp and SoundCloud are working fine. And I've changed nothing at my end, this just suddenly stopped working without me doing anything. I've tried disabling Ublock Origin on the web page as well but that made no difference either.

**Comment by KatyLB** [comment]
I would try that, but I don't know how to? However, I was using an older version of the extension when this broke already, and updated to see if it would fix it.

**Comment by alexesprit** [comment]
https://addons.mozilla.org/en-US/firefox/addon/web-scrobbler/versions/

But if you say it was broken in previous versions, I doubt if downgrade helps. Perhaps, it's something changed on YouTube side.

Also, do you use addons that change YouTube interface? Or maybe do other addons break Web Scrobbler somehow?

**Comment by KatyLB** [comment]
I've got it working (although weirdly this didn't work first time) by turning off both of the YouTube options, for the Music and Entertainment category.

The songs aren't in other categories, though, they're all music or entertainment.

_But_, what I've noticed is that underneath YouTube videos isn't showing the "category" of videos anymore:

![image](https://user-images.githubusercontent.com/37089178/79691510-f0169980-8257-11ea-83e7-1108d20e33ab.png)

Could this be the problem? If they've removed the categories, I guess that would make it stop working?

**Comment by alexesprit** [comment]
Yes, probably. But it should scrobble if a category is missing. I will check that.

I have a "Music" category for the "Blur - Song 2", if I expand the video description.
![image](https://user-images.githubusercontent.com/1119267/79691668-a46ceb80-8269-11ea-9bff-83eae4b7a99b.png)

**Comment by alexesprit** [comment]
Yes, it does not work because of the missing category. Will try to fix it.

**Comment by alexesprit** [comment]
I published v2.30.6 where I tried to fix the issue. Could you check this version?

**Comment by KatyLB** [comment]
It still doesn't work unless I have those checkboxes unchecked.

**Comment by alexesprit** [comment]
It should work even if those options are turned on. Make sure you have the extension updated.

**Comment by KatyLB** [comment]
I don't know how to manually update the add-on, but I restarted my browser and it's showing as v2.30.6:

![image](https://user-images.githubusercontent.com/37089178/79692526-931de200-825d-11ea-8373-e9ae3647749d.png)

**Comment by alexesprit** [comment]
That's sad. I have no more ideas.

**Comment by KatyLB** [comment]
It seems to have started working now. I don't know why it didn't the first time. Seems like updating the add-on didn't take effect until I tried a few times...
