### ISSUE TITLE
navidrome track scrobbles include audio quality next to song title

### ISSUE THREAD

**Issue by ducky710** [web-scrobbler/web-scrobbler#2828]
This is a really simple bug I'd assume. Basically Navidrome added a new feature that includes a little flag next to track titles that show whether tracks are FLAC or 320 or V0 etc and they have started being scrobbled along with the song titles. 

![image](https://user-images.githubusercontent.com/63337938/115653391-0dfc5b80-a2fd-11eb-815c-80e2240bd0cf.png)

![image](https://user-images.githubusercontent.com/63337938/115653477-3dab6380-a2fd-11eb-95e5-59a1757b6170.png)

![image](https://user-images.githubusercontent.com/63337938/115653503-4a2fbc00-a2fd-11eb-8cf5-7965bacae7da.png)

**Comment by deluan** [comment]
This is happening with the latest development build. I'll try to fix this from Navidrome's side before next release.

**Comment by ducky710** [comment]
Oh hey thanks man. Didn't expect to see you here! Appreciate it 😊 Big fan of Navidrome.

**Comment by deluan** [comment]
Hey @ducky710, can you try this with the latest Navidrome build? Should be fixed.

**Comment by ducky710** [comment]
Just pulled the image and tried it and it seems its still happening. Must be totally on web-scrobblers end.

**Comment by deluan** [comment]
Did you force refresh the UI? You should see in the About dialog box: 0.41.0-SNAPSHOT (3cede281)

> Must be totally on web-scrobblers end.

I'm pretty confident I can fix on Navidrome's side

**Comment by ducky710** [comment]
Apologies, I am for sure on that image however I hadn't cleared cache. Just did that and you're right you did fix the issue of the quality going with the track title, but now it scrobbles absolutely nothing :joy: . It doesn't recognize any parts of the track or artist names even with force recognition on. 
![image](https://user-images.githubusercontent.com/63337938/115976244-fcec5e00-a539-11eb-84b7-607f4c3223bb.png)

**Comment by deluan** [comment]
Ops.... Yeah, I thought it would be a simple change. I'll have to install Web Scrobbler to test it locally.

**Comment by ducky710** [comment]
I really appreciate the effort man. Do you have a buy me a coffee or anything like that link? Will def toss you a few bucks once you get it settled.

**Comment by deluan** [comment]
Hey @ducky710, try again. Latest build (4b5a5ab) should be good to go. I tested it locally and it worked as expected.

**Comment by ducky710** [comment]
It's perfect now! Thanks a lot! :heart:
