### ISSUE TITLE
Extension not recognizing tracks are playing. (Spotify Chrome)

### ISSUE THREAD

**Issue by 0edit** [web-scrobbler/web-scrobbler#3575]
**Describe the bug**
The extension does not scobble/recognize that a track is playing when using Spotify web player for Chrome. Tried switching around remaining time to no avail. Restarted browser etc. Works fine on other sites like Bandcamp,Soundcloud, etc.

**How to reproduce**
1. Go to Spotify
2. Play track
3. Look at extension, it is not lit green and track is not being recognized. Therefore, it is not scrobbling. 

**Expected behavior**
When I play a track, it should be recognized on the extension.

**Screenshots**

**Debug logs**
<details>Bind Last.fm scrobbler
scrobble-service.js:55 Unable to bind Libre.fm
bindAllScrobblers @ scrobble-service.js:55
scrobble-service.js:55 Unable to bind ListenBrainz
bindAllScrobblers @ scrobble-service.js:55
scrobble-service.js:55 Unable to bind Maloja
bindAllScrobblers @ scrobble-service.js:55
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/browser-polyfill.min.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/md5.min.js.map: System error: net::ERR_FILE_NOT_FOUND
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/spotify.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 1992117217: Created controller for Spotify connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/bandcamp.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 1992117224: Created controller for Bandcamp connector
util.js:40 Tab 1992117217: Remove controller for Spotify connector
util.js:40 Tab 1992117224: New song detected: {
  "track": "Install Now",
  "artist": "Win7Ult [CRACKED].iso",
  "album": "5",
  "albumArtist": null,
  "uniqueID": null,
  "duration": 114,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://f4.bcbits.com/img/a2976221667_16.jpg",
  "isPodcast": false,
  "originUrl": "https://seasidebliss.co/album/5"
}
scrobble-service.js:97 Send "get info" request: 1
util.js:40 Last.fm: track.getinfo response:
{
  "error": 6,
  "message": "Track not found",
  "links": []
}
scrobble-service.js:101 Unable to get song info from Last.fm
(anonymous) @ scrobble-service.js:101
Promise.catch (async)
(anonymous) @ scrobble-service.js:100
getSongInfo @ scrobble-service.js:99
process @ metadata.js:29
process @ pipeline.js:25
await in process (async)
processSong @ controller.js:338
processNewState @ controller.js:291
onStateChanged @ controller.js:218
processPortMessage @ tab-worker.js:122
(anonymous) @ extension.js:122
coverartarchive.js:10 Using local/parsed artwork
util.js:40 Tab 1992117224: Song finished processing: {
  "parsed": {
    "track": "Install Now",
    "artist": "Win7Ult [CRACKED].iso",
    "album": "5",
    "albumArtist": null,
    "uniqueID": null,
    "duration": 114,
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://f4.bcbits.com/img/a2976221667_16.jpg",
    "isPodcast": false,
    "originUrl": "https://seasidebliss.co/album/5"
  },
  "processed": {
    "track": null,
    "album": null,
    "artist": null,
    "albumArtist": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  },
  "metadata": {
    "startTimestamp": 1676403327,
    "label": "Bandcamp"
  },
  "connectorLabel": "Bandcamp"
}
util.js:40 Tab 1992117224: The song will be scrobbled in 57 seconds
util.js:40 Tab 1992117224: The song will be repeated in 114 seconds
scrobble-service.js:113 Send "now playing" request: 1
util.js:40 Last.fm: track.updatenowplaying response:
{
  "nowplaying": {
    "artist": {
      "corrected": "0",
      "#text": "Win7Ult [CRACKED].iso"
    },
    "track": {
      "corrected": "0",
      "#text": "Install Now"
    },
    "ignoredMessage": {
      "code": "0",
      "#text": ""
    },
    "albumArtist": {
      "corrected": "0",
      "#text": ""
    },
    "album": {
      "corrected": "0",
      "#text": "5"
    }
  }
}
util.js:40 Tab 1992117224: Song set as now playing</details>

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.86.0

**Additional context**

**Comment by Wyyvern** [comment]
Came here to report the same issue on the brave browser (which is basically reskinned chrome)

**Comment by jetdzhet** [comment]
Same thing happens on Firefox

**Comment by inverse** [comment]
Just released https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.86.1 which should resolve it.

Unfortunately getting approval in Firefox addons takes some time :/ Chrome is usually quicker.

**Comment by sc113** [comment]
2.86.1 in Chrome still not working for me. The icon is red all the time

**Comment by jetdzhet** [comment]
In Firefox, version 2.86.1 seems not to have been approved yet, little question, how long does it usually take for Firefox to give the green light to extension updates?

**Comment by yayuyokitano** [comment]
> In Firefox, version 2.86.1 seems not to have been approved yet, little question, how long does it usually take for Firefox to give the green light to extension updates?

It has been faster before, but in recent months I have found it to take about 4-5 days for mozilla to approve updates on average.
