### ISSUE TITLE
Mixcloud Scrobbling Not Working on Firefox

### ISSUE THREAD

**Issue by EmoSheeran** [web-scrobbler/web-scrobbler#5308]
**Describe the bug**
The web scrobbler on Firefox doesn't scrobble songs. It doesn't register anything is playing and only says 'Play some music to get started'. 

**How to reproduce**
Try playing a track on Mixcloud.

**Expected behavior**
The web scrobbler should register a song is playing.

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Firefox
-   Extension version: v3.10.0

**Additional context**
I've had this issue for at least a year now and I might've reported it before, though I can't find my original request.

**Comment by kxkv** [comment]
I can verify this. Using Linux. Latest Firefox. Same issue.

**Comment by Obey138** [comment]
Also doesn't work on Chrome 137.0.7151.69 on Windows 10
Extension version 3.14.0

**Comment by cairobraga** [comment]
Not working on Chrome 138 on Windows 11, extension version 3.14.

And not working on LibreWolf 139 on Ubuntu 24.04, extension version 3.10.

**Comment by hans-juergen** [comment]
Still broken for me (Edge, Windows 10 Pro, Web Scrobbler for Chrome 3.15.0) despite the fixes last December. Here are the related threads and pull requests:

https://github.com/web-scrobbler/web-scrobbler/pull/5093
https://github.com/web-scrobbler/web-scrobbler/pull/5063
https://github.com/web-scrobbler/web-scrobbler/issues/4970
https://github.com/web-scrobbler/web-scrobbler/issues/4758

I was checking the Last.fm support FAQs containing the broken Web Scrobbler home page URL web-scrobbler.com and replaced it with the new webscrobbler.com one, that is how I noticed the broken Mixcloud connector. Mixcloud does not have an internal scrobbling option anymore, so Web Scrobbler would be the only alternative:
https://support.last.fm/t/mixcloud-scrobbling/178

**Comment by Irick** [comment]
Same issue, Linux, Latest Firefox, version 3.16.0 of the extension.

**Comment by scy** [comment]
This was supposedly fixed by #5626, which is unreleased as of today. The current version, 3.17.0, was released two days prior and doesn't have that fix yet.

**Comment by nvqna** [comment]
Chrome version 141.0.7390.123 with WebScrobbler version 3.18.0 also isn't scrobbling from Mixcloud.

<img width="2035" height="987" alt="Image" src="https://github.com/user-attachments/assets/256078c2-71e4-4551-9bbe-c7b42403a5e5" />

**Comment by merepseud-pixel** [comment]
Still not working [Brave 1.84.139 (Official Build) (arm64)](https://brave.com/latest/)
Chromium: 142.0.7444.163]. 

![Image](https://github.com/user-attachments/assets/7fcb9301-33dd-476b-b37c-f9f6b1bcc071)

**Comment by gdedas** [comment]
still not working....

- WS version 3.18.0
- 147.0.2 (64-bit) Firefox
- Ubuntu 22.04.5 LTS

**Comment by gdedas** [comment]
sorry, but it is still not working

**Comment by rob9315** [comment]
@gdedas are you using v3.21 from the repo that has the fix for it?

**Comment by gdedas** [comment]
thanks for the hint, it now works on v3.21 !
