### ISSUE TITLE
Web Scrobbler doesn't scrobble from VK (From today)

### ISSUE THREAD

**Issue by c0ntr-all** [web-scrobbler/web-scrobbler#5400]
**Describe the bug**
Doesn't scrobble from vk playlists. It was appeared today, at about 14:00 (Moscow). I managed to scrobble a few tracks, but after reloading the page, scrobbling stopped working.

**How to reproduce**
1. Go to any playlist in vk
2. Click on any track
3. See how web scrobbler doesn't scrobble!

![Image](https://github.com/user-attachments/assets/7b6081af-f980-448d-bd4f-7a955e57778f)

**Comment by ghost** [comment]
doesn't work for spotify too, when the issue will be fixed i wonder

**Comment by Gghanansnsn** [comment]
Same thing here, it scrobbled at first but then stopped after reloading the page. I also use the same browser as the OP. A significant portion of last.fm users are from post-Soviet countries and most of them scrobble from VK, so please fix this, dear developers!

**Comment by Huterenok** [comment]
I also sometimes face this issue while using scrobbler for VK in Chrome, but it's usually fixed by simply restarting browser. Currently cannot reproduce bug. Are there any specific actions before bug occurs?

P.S. my friend who uses web scrobbler for Spotify also faces this issue

**Comment by Gghanansnsn** [comment]
No any specific actions, it just doesn't scrobble no matter what I try to do, restarting the browser doesn't solve the issue as well. I simply open the browser, then open vk.com, play a track and that's it - then the extention's logo turns red just as it is seen on the OP's screenshot and that is pretty much it, nothing scrobbles on VK. It does on bandcamp for instance, though.

**Comment by ExpandingShapes** [comment]
same

**Comment by rob9315** [comment]
I cannot reproduce this issue.

<details><summary>scrobbles just fine for me (screenshots)</summary>
normal track
<img width="1410" height="964" alt="Image" src="https://github.com/user-attachments/assets/cfc9b3df-47ab-4821-8bcd-7cd7cd427aa3" />
playlist
<img width="1410" height="964" alt="Image" src="https://github.com/user-attachments/assets/f6d80435-6f49-4ce7-affd-272773da0b7d" />
</details>

Could you please give a specific link / specific instructions on how to reproduce the problem?, and please more information about your environment (browser, extension version, etc etc)
