### ISSUE TITLE
Website redirecting to spam and malware sites

### ISSUE THREAD

**Issue by ethicalrevolution** [web-scrobbler/web-scrobbler#5520]
With caution, see https://web-scrobbler.com/ - seems to have been compromised.

**Comment by 1shira** [comment]
website is on https://webscrobbler.com/

**Comment by ethicalrevolution** [comment]
Ace, this will need to be updated on the extensions page in Firefox etc.

<img width="671" height="454" alt="Image" src="https://github.com/user-attachments/assets/c88e6cd2-5cc0-4ae0-88cf-afc8f3decf1f" />

**Comment by inverse** [comment]
Thanks for reporting this, PRing changes, etc

I've updated the reference on Firefox page but not sure why its not changed yet.

The PR with URLS in the extension itself have been updated and we will need to publish a new version to get that out.

Updated the meta tags on the site itself in https://github.com/web-scrobbler/web-scrobbler.github.io/pull/335

Anywhere else you noticed it wrong?

**Comment by ethicalrevolution** [comment]
That's it for me. We're about to publish an article on https://nham.co.uk about the web scrobbler but will wait until the links have updated before doing so. Also, can you confirm that https://webscrobbler.com/ is now the correct url to direct people to? (We'll include this in the article).

**Comment by ABrokenRadio** [comment]
I know Libre.fm is in maintenance mode or whatever and not sure how much it gets used but there is a link on the recent tracks page that uses the bad url.

<img width="794" height="627" alt="Image" src="https://github.com/user-attachments/assets/58dc8f49-64fa-41e9-b81b-03bd91802ea5" />

That goes to the web-scrobbler.com version. Should probably see about getting that fixed to if you can.

**Comment by inverse** [comment]
@ethicalrevolution it is the correct URL that we will use going forward


@ABrokenRadio how do you get to this page? I can't see it when I login.

**Comment by ABrokenRadio** [comment]
@invere I'm on mobile right now but I couldn't find it either when I went back to check. Pretty sure it was on the recent track page, but I'll double check when I get to my desktop, but it might have been fix/removed by now.

edit: got around to rechecking the site, and i couldn't find it anymore. So looks like it got removed.

**Comment by ethicalrevolution** [comment]
> [@ethicalrevolution](https://github.com/ethicalrevolution) it is the correct URL that we will use going forward
> 
Great, I've just published the post: https://nham.co.uk/2025/10/scrobble-baby/

**Comment by rob9315** [comment]
@inverse it's also on the twitter account

<img width="616" height="410" alt="Image" src="https://github.com/user-attachments/assets/132d7a0d-ffae-4c23-9c10-ec1c1179ba74" />

that the github org links to

<img width="595" height="159" alt="Image" src="https://github.com/user-attachments/assets/de052596-7d0f-4c80-81d5-1f14bbfc2a35" />

**Comment by hans-juergen** [comment]
@inverse: The outdated URL with the hyphen also still appears on the App Store page for the Safari version at the bottom in the link to the developer website and privacy policy:

https://apps.apple.com/app/web-scrobbler/id6449224218?platform=iphone

**Comment by rob9315** [comment]
<details>
  <summary>the edge add-on store also still directs users to the old domain</summary>
  
<img width="1235" height="485" alt="Image" src="https://github.com/user-attachments/assets/5dce89c7-ed2d-45aa-b6fa-28337d4b21e7" />
</details>

https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc
